# Generated by Django 4.2.11 on 2026-04-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ARMADO', 'En armado'), ('FINALIZADO', 'Finalizado')], default='ARMADO', max_length=15)),
                ('lotes_materia_prima', models.ManyToManyField(to='gestion_materia_prima.lotemateriaprima')),
            ],
        ),
    ]
