# Generated by Django 4.2.11 on 2026-04-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_materia_prima', '0001_initial'),
        ('gestion_produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproduccion',
            name='lotes_materia_prima',
            field=models.ManyToManyField(related_name='lotes_produccion', to='gestion_materia_prima.lotemateriaprima', verbose_name='Lotes de materia prima'),
        ),
        migrations.CreateModel(
            name='ProductoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=24, unique=True)),
                ('tipo', models.CharField(choices=[('ACEITE', 'Aceite'), ('ACEITUNA_MESA', 'Aceituna de mesa')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('L', 'Litros'), ('KG', 'Kilogramos'), ('UD', 'Unidades')], default='L', max_length=5)),
                ('descripcion', models.TextField(blank=True)),
                ('lote_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_finales', to='gestion_produccion.loteproduccion')),
            ],
        ),
    ]
