# Generated by Django 4.2.11 on 2026-04-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=24, unique=True)),
                ('fecha_cosecha', models.DateField()),
                ('fecha_arribo', models.DateTimeField(auto_now_add=True)),
                ('peso_bruto', models.FloatField()),
                ('peso_tara', models.FloatField()),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('ANALISIS', 'En análisis'), ('ANALIZADO', 'Analizado'), ('ASIGNADO', 'Asignado a Lote de producción')], default='INGRESADO', max_length=20)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.productor')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_analisis', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='gestion_materia_prima.lotemateriaprima')),
            ],
        ),
    ]
